# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "clone"
  - "build"
  - "test"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "anais-codefresh/selenium-example"
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "clone"

  build_image:
    title: "Building Docker image"
    type: "build"
    image_name: "anaisurlichs/selenium-example"
    working_directory: "${{clone}}"
    tag: "1.0.0"
    dockerfile: "Dockerfile"
    stage: "build"
    
  test:
    title: "Running test"
    type: "freestyle" # Run any command
    image: "anaisurlichs/selenium-example:1.0.0" # The image in which command will be executed
    working_directory: "${{clone}}" # Running command where code cloned
    stage: "test"